### PR TITLE
Fmod

### PR DESCRIPTION
**Pull request by cmeese549**
Fmod

### CODE REVIEW

**Comment by jakemcleman** [comment]
I ask because I have a vague memory of this being a thing and don't know how to look for it in the changeset. I seem to remember fmod requiring being on our splash screen as a license requirement. Does this include that? Or am I not remembering good.

**Comment by cmeese549** [comment]
Good question, it isn't there yet, but that is because the entire splashcreen isn't there yet.  I'm working rn on a cool sound logo thing for the splashscreen and then I'm going to put that in another branch, which will rely on this branch to actually play the audio.  I will def include the logo there, even though I can't remember the rules about it.

**Comment by jakemcleman** [comment]
I think you'll need to pull main onto this again since I just fixed an issue in the config where the self-hosted runners were only half existing

**Comment by cmeese549** [comment]
Epic pull has been did

**Comment by ewulff** [comment]
What's up with this error? 

`FMOD Studio: The FMOD Studio project path must be set to an .fspro file.`

**Comment by cmeese549** [comment]
> What's up with this error?
> 
> `FMOD Studio: The FMOD Studio project path must be set to an .fspro file.`

That error would happen if the fmod settings .asset file thingy is missing, I'm trying to figure out wtf is happening rn

**Review by jakemcleman — APPROVED** [review]

**Pull request merged**
